### ISSUE TITLE
The server panics on existing `/tmp/tb_data` and `/tmp/tb_schema`

### ISSUE THREAD

**Issue by whjpji** [tensorbase/tensorbase#183] opened 2021-07-08 15:50 UTC
I recompiled TB today and ran the server, and it paniced.
```
cargo run --color=always --bin server -- -c ./crates/server/tests/confs/base.conf
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
     Running `/opt/cargo/target/debug/server -c ./crates/server/tests/confs/base.conf`
15:40:26 [INFO] [Base] built in debug mode
15:40:26 [INFO] confs to use:
15:40:26 [INFO] system.meta_dirs: ["/tmp/tb_schema"]
15:40:26 [INFO] system.data_dirs: ["/tmp/tb_data"]
15:40:26 [INFO] server.ip_addr: "localhost"
15:40:26 [INFO] server.port: 9528
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WrappingMetaError(OpenError)', crates/runtime/src/mgmt.rs:152:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/core/src/result.rs:1037:23
   4: runtime::mgmt::BMS::{{closure}}
             at ./crates/runtime/src/mgmt.rs:152:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/core/src/ops/function.rs:227:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/core/src/ops/function.rs:227:5
   7: std::lazy::SyncLazy<T,F>::force::{{closure}}
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/lazy.rs:565:24
   8: std::lazy::SyncOnceCell<T>::get_or_init::{{closure}}
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/lazy.rs:249:50
   9: std::lazy::SyncOnceCell<T>::initialize::{{closure}}
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/lazy.rs:430:19
  10: std::sync::once::Once::call_once_force::{{closure}}
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/sync/once.rs:319:40
  11: std::sync::once::Once::call_inner
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/sync/once.rs:418:21
  12: std::sync::once::Once::call_once_force
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/sync/once.rs:319:9
  13: std::lazy::SyncOnceCell<T>::initialize
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/lazy.rs:429:9
  14: std::lazy::SyncOnceCell<T>::get_or_try_init
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/lazy.rs:296:9
  15: std::lazy::SyncOnceCell<T>::get_or_init
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/lazy.rs:249:15
  16: std::lazy::SyncLazy<T,F>::force
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/lazy.rs:564:9
  17: <std::lazy::SyncLazy<T,F> as core::ops::deref::Deref>::deref
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/lazy.rs:575:9
  18: server::main::{{closure}}
             at ./crates/server/src/server.rs:49:17
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/core/src/future/mod.rs:80:19
  20: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/task/local.rs:528:65
  21: tokio::coop::with_budget::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/coop.rs:127:9
  22: std::thread::local::LocalKey<T>::try_with
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/thread/local.rs:399:16
  23: std::thread::local::LocalKey<T>::with
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/thread/local.rs:375:9
  24: tokio::coop::with_budget
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/coop.rs:120:5
  25: tokio::coop::budget
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/coop.rs:96:5
  26: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/task/local.rs:528:42
  27: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  28: tokio::task::local::LocalSet::with
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/task/local.rs:442:9
  29: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/task/local.rs:518:9
  30: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/task/local.rs:392:9
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/core/src/future/mod.rs:80:19
  32: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:58
  33: tokio::coop::with_budget::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/coop.rs:127:9
  34: std::thread::local::LocalKey<T>::try_with
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/thread/local.rs:399:16
  35: std::thread::local::LocalKey<T>::with
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/std/src/thread/local.rs:375:9
  36: tokio::coop::with_budget
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/coop.rs:120:5
  37: tokio::coop::budget
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/coop.rs:96:5
  38: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:35
  39: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:29
  40: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  41: tokio::runtime::basic_scheduler::enter
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:5
  42: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/basic_scheduler.rs:123:9
  43: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/mod.rs:444:34
  44: tokio::runtime::context::enter
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/context.rs:72:5
  45: tokio::runtime::handle::Handle::enter
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/handle.rs:76:9
  46: tokio::runtime::Runtime::block_on
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/runtime/mod.rs:441:9
  47: tokio::task::local::LocalSet::block_on
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-0.2.25/src/task/local.rs:353:9
  48: actix_rt::runtime::Runtime::block_on
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/actix-rt-1.1.1/src/runtime.rs:89:9
  49: actix_rt::builder::SystemRunner::block_on
             at /home/whjpji/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/actix-rt-1.1.1/src/builder.rs:187:19
  50: server::main
             at ./crates/server/src/server.rs:21:1
  51: core::ops::function::FnOnce::call_once
             at /rustc/e6b4c252ea33e9f80ab8b8d7b3f6393e54166127/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread.

Process finished with exit code 101
```

After removing the two directories and creating new ones, it ran successfully.

Since it happened in the `Mgmt::from_conf`, I think it is probably related to the directory creating process.

**Comment by jinmingjian** [comment] 2021-07-08 23:57
@whjpji early panics is wanted if prerequisite can not be reached. But for your case, it said ```OpenError``` (this err message need improved). There are several reasons for this: 
1. permission for dir/file; (not likely)
2. meta/schema broken; 
3. changes to source causes the problem;
4. soft bug causes the problem;
Can you provide original schema and/or data info? It is better to copy the original schema and/or data directories for further investigation.

**Comment by whjpji** [comment] 2021-07-09 00:04
[tb_schema_with_data.tar.gz](https://github.com/tensorbase/tensorbase/files/6787835/tb_schema_with_data.tar.gz)

@jinmingjian Here is the original schema and data info.

**Comment by jinmingjian** [comment] 2021-07-09 00:19
Your meta works for me!
```
TensorBase :) show tables

SHOW TABLES

Query id: d5c9bd20-5998-4e81-96c0-9ea3b08e463d

┌─name──────────┐
│ test_fixed    │
│ test_datetime │
└───────────────┘

2 rows in set. Elapsed: 0.007 sec.
```

It is confirmed that the issue can not be reproduced. I close this issue if no problem.

**Closed by jinmingjian** 2021-07-09 00:19 UTC
Labels: status/pending
