### ISSUE TITLE
support FixedString type

### ISSUE THREAD

**Issue by jinmingjian** [tensorbase/tensorbase#53] opened 2021-05-01 01:11 UTC
another fixed length type

**Comment by jinmingjian** [comment] 2021-05-10 07:12
this is not necessary for running TPC-H

**Comment by Thysinner** [comment] 2021-05-21 06:18
I found that the CH `FixedString` is just the same data type as Arrow `FixedSizeBinary` with a different name. So the simplest way might be to add an alias for the existed `FixedSizeBinary` type.

**Comment by jinmingjian** [comment] 2021-05-21 07:14
@Thysinner  Basically yes. TB has it own data type called BqlType. So there is no "alias" concept, strictly speaking. But you can show your codes. Any reasonable implementation is welcome.

**Comment by whjpji** [comment] 2021-05-23 05:34
I think the main difference between TB's `FixedString` and Arrow's `FixedSizeBinary` is, that the `FixedString` type is a string which has its length and encoded data, but `FixedSizeBinary` is just raw bytes.

I'm considering such an implementation:

Decided by the max length of `FixedString`, the max length of corresponding `FixedSizeBinary` should be the maximum bytes needed to store its length (possibly a `u8`, `u16`, or `u24` etc.) plus its length in bytes.

**Comment by jinmingjian** [comment] 2021-05-23 05:51
@whjpji thanks for your analysis! 
> that the FixedString type is a string which has its length and encoded data
this is not true. Because TB has no FixedString and this issue is trying to fix this. For TB's String, this saying is basically ok.(But this current layout of String may be temporary.)

So, the simple and enough way for FixedString, is just that mapping to Arrow's FixedSizeBinary. The length of FixedString is just a kind of meta which is stored in the schema. 

A little more work for this issue is that you need to add this type to the decoding path. If you are interesting, we can discuss more.

**Comment by whjpji** [comment] 2021-05-23 06:25
Thanks @jinmingjian!

Consider there is a `FixedSring(10)` which has length `10`, and the user writes a string `"test"` to it. According to your discription, the stored data should be: `b"test\x00\x00\x00\x00\x00\x00"`, exactly 10 bytes.

In my understanding, when this `FixedString` is read and displayed to the user, it should also be `"test"` as same as it is inserted. However, from the metadata we know the length of this `FixedString` type is `10`, and thus it is decoded to `test\x00\x00\x00\x00\x00\x00"`in UTF-8, which is different from the user's input.

In such layout, a possibly solution might be assuming the string is ended when encountered with a zero (`'\x00'`), which is much more like zero-ended strings in C.

You cannot get the **real** length of the `FixedString`'s content (except assuming it zero-ended and scanning the whole contended UTF-8 bytes). As I described above, `FixedString` just means the size of its storage is fixed, but not means the length of the stored string is fixed, because *length* is just a inherited inherent property of a string.

**Comment by jinmingjian** [comment] 2021-05-23 06:39
@whjpji Yes. This is inherent from CH. So, it is better that we firstly implement it for the compatibility.

Furthermore, the display and its interpolation is not important. It is just a fixed string, which is **not** String. If you want String behavior, you just use String.

**Comment by whjpji** [comment] 2021-05-23 06:51
@jinmingjian Yes you are right, `FixedString` is not `String`. 

I found the document of `FixedString` in CH [1]. It is coherent with you description. I'd like to have a try to implement `FixedString` using Arrow's `FixedSizeBinary`.

[1] https://clickhouse.tech/docs/en/sql-reference/data-types/fixedstring/

**Comment by jinmingjian** [comment] 2021-05-23 07:41
@whjpji Great! Let's start the prototype and see the outcome!

**Comment by Thysinner** [comment] 2021-05-24 02:43
@jinmingjian @whjpji  Seems there's a task conflict. I suggest that we could use a task assignment mechanism to avoid task conflicts. Otherwise, it is likely to waste time because multiple people are doing repetitive tasks.
For example, if someone is interested in an issue, he can invoke `assign` command and others will know the issue is already assigned. However, if an issue is critical, it should be assigned to someone who is already very familiar with the project.

**Comment by jinmingjian** [comment] 2021-05-24 02:51
@Thysinner thanks for your idea. 

Most people shows interests but will not do coding. TB is opensource culture community. **For external contributors, it is not appropriate to assign tasks unless this been requested explicitly.** 

The better way is that you show that you want to fix this issue in that issue. And everyone knows that you are working on this. Then they will try other issues.

**Comment by Thysinner** [comment] 2021-05-24 03:27
> The better way is that you show that you want to fix this issue in that issue. And everyone knows that you are working on this. Then they will try other issues.

I do mean this. However, I think it's my stupid mistake that I forgot to told that I am in the progress of this issue and it's almost done. 😁

**Closed** 2021-05-24 23:18 UTC
Labels: challenge/two-hour-feat-flash, component/engine, difficulty/newcomer, good first issue
