### ISSUE TITLE
INSERT failed if click clickhouse-client version >=21.5 without --compression arg

### ISSUE THREAD

**Issue by pymongo** [tensorbase/tensorbase#117] opened 2021-06-04 03:43 UTC
I tried to cell_towers csv data from clickhouse <https://clickhouse.tech/docs/en/getting-started/example-datasets/cell-towers/>

I follower the step 5:
> clickhouse-client --query "INSERT INTO cell_towers FORMAT CSVWithNames" < cell_towers.csv

Here is my operation:

```
[w@ww Downloads]$ head cell_towers.csv 
radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal
UMTS,262,2,801,86355,0,13.285512,52.522202,1000,7,1,1282569574,1300155341,0
GSM,262,2,801,1795,0,13.276907,52.525714,5716,9,1,1282569574,1300155341,0
GSM,262,2,801,1794,0,13.285064,52.524,6280,13,1,1282569574,1300796207,0
UMTS,262,2,801,211250,0,13.285446,52.521744,1000,3,1,1282569574,1299466955,0
UMTS,262,2,801,86353,0,13.293457,52.521515,1000,2,1,1282569574,1291380444,0
UMTS,262,2,801,86357,0,13.289106,52.53273,2400,3,1,1282569574,1298860769,0
UMTS,262,3,1107,83603,0,13.349675,52.497575,3102,222,1,1282672189,1300710809,0
GSM,262,2,776,867,0,13.349711,52.497367,1000,214,1,1282672189,1301575206,0
GSM,262,3,1107,13971,0,13.349743,52.497437,1000,212,1,1282672189,1300710809,0
[w@ww Downloads]$ du -h cell_towers.csv
3.5G    cell_towers.csv
[w@ww Downloads]$ clickhouse-client --port 9528 --query "INSERT INTO cell_towers.cell_towers FORMAT CSVWithNames" < cell_towers.csv
Received exception from server (version 2021.5.0):
Code: 4. DB::Exception: Received from localhost:9528. WrappingLangError(ASTError(" --> 1:51\n  |\n1 | INSERT INTO cell_towers.cell_towers FORMAT CSVWithNames\n  |                                                   ^---\n  |\n  = expected table_name_numbers")). Error when AST processing:  --> 1:51
  |
1 | INSERT INTO cell_towers.cell_towers FORMAT CSVWithNames
  |                                                   ^---
  |
  = expected table_name_numbers.
```

**Comment by jinmingjian** [comment] 2021-06-04 05:13
@pymongo ```FORMAT CSVWithNames``` is not welled tested.  One workaround is, to just remove the head line in that csv

**Comment by pymongo** [comment] 2021-06-04 14:08
still got error when I execute `clickhouse-client --port 9528 --query "INSERT INTO cell_towers" < cell_towers_no_headers.csv`

```
[w@ww Downloads]$ clickhouse-client --port 9528 --query "INSERT INTO cell_towers" < cell_towers_no_headers.csv
Code: 62. DB::Exception: Syntax error: failed at position 24 (end of query): . Expected one of: WATCH, OpeningRoundBracket, SELECT, VALUES, FORMAT, Dot, WITH, token

[w@ww Downloads]$ head -n 5 cell_towers_no_headers.csv
LTE,405,854,170,296498,-1,78.394203,17.498991,1000,2,1,1608614488,1608614494,0
LTE,405,854,170,6703921,-1,78.392855,17.499416,1000,4,1,1608614519,1608614549,0
LTE,405,854,170,6703920,-1,78.391823,17.501488,1000,1,1,1608614594,1608614594,0
LTE,405,854,170,6703891,-1,78.391838,17.501476,1000,1,1,1608614613,1608614613,0
LTE,405,854,170,296467,-1,78.393715,17.503044,1000,1,1,1608614664,1608614664,0
```

**Comment by jinmingjian** [comment] 2021-06-05 00:40
@pymongo thanks for feedback, I will have a check late today

**Comment by luluai-cn** [comment] 2021-06-05 07:36
@pymongo can't reproduce , my steps:

1. new csv without header

> [roy@LAPTOP workspace/csv]$ sed 1d cell_towers.csv >> cell_towers_no_headers.csv
> [roy@LAPTOP workspace/csv]$ head -n 3 cell_towers_no_headers.csv
> UMTS,262,2,801,86355,0,13.285512,52.522202,1000,7,1,1282569574,1300155341,0
> GSM,262,2,801,1795,0,13.276907,52.525714,5716,9,1,1282569574,1300155341,0
> GSM,262,2,801,1794,0,13.285064,52.524,6280,13,1,1282569574,1300796207,0

2. import data from csv

> clickhouse-client --port 9528 --query "INSERT INTO cell_towers.cell_towers FORMAT CSV" < cell_towers_no_headers


3. query data from db

> 
> TensorBase :) select count(*) from cell_towers
> 
> SELECT count(*)
> FROM cell_towers
> 
> Query id: 3cb8bc02-a10f-4be8-a759-a4f82ee5779d
> 
> ┌─COUNT(UInt8(1))─┐
> │        43276158 │
> └─────────────────┘
> 
> 1 rows in set. Elapsed: 0.854 sec.

**Comment by pymongo** [comment] 2021-06-09 08:56
both my desktop(amd 5900X) and laptop can reproduce this problem when I insert cell_towers csv data.

Should I need a ubuntu OS to test this problem?

## tensorbase create cell_towers database and table
```
TensorBase :) create database cell_towers

CREATE DATABASE cell_towers

Query id: c79aad98-7b71-48f4-9393-6adaf493fc6b

Ok.

0 rows in set. Elapsed: 0.003 sec. 

TensorBase :) use cell_towers

USE cell_towers

Query id: 772e9d02-4f5a-4a9d-b2d7-08238c9e92bf

Ok.

0 rows in set. Elapsed: 0.001 sec. 

TensorBase :) CREATE TABLE cell_towers
:-] (
:-]     radio String,
:-]     mcc UInt16,
:-]     net UInt16,
:-]     area UInt16,
:-]     cell UInt64,
:-]     unit Int16,
:-]     lon Float64,
:-]     lat Float64,
:-]     range UInt32,
:-]     samples UInt32,
:-]     changeable UInt8,
:-]     created DateTime,
:-]     updated DateTime,
:-]     averageSignal UInt8
:-] )
:-] ENGINE = BaseStorage

CREATE TABLE cell_towers
(
    `radio` String,
    `mcc` UInt16,
    `net` UInt16,
    `area` UInt16,
    `cell` UInt64,
    `unit` Int16,
    `lon` Float64,
    `lat` Float64,
    `range` UInt32,
    `samples` UInt32,
    `changeable` UInt8,
    `created` DateTime,
    `updated` DateTime,
    `averageSignal` UInt8
)
ENGINE = BaseStorage

Query id: 07548058-4f79-4a51-911b-702244c0bbb5

Ok.

0 rows in set. Elapsed: 0.008 sec. 

TensorBase :) exit
Bye.
```

## the csv data file
(first 10 record from clickhouse's cell_towers sample)
```
[w@w-manjaro Downloads]$ cat cell_towers_no_headers.csv 
UMTS,262,2,801,86355,0,13.285512,52.522202,1000,7,1,1282569574,1300155341,0
GSM,262,2,801,1795,0,13.276907,52.525714,5716,9,1,1282569574,1300155341,0
GSM,262,2,801,1794,0,13.285064,52.524,6280,13,1,1282569574,1300796207,0
UMTS,262,2,801,211250,0,13.285446,52.521744,1000,3,1,1282569574,1299466955,0
UMTS,262,2,801,86353,0,13.293457,52.521515,1000,2,1,1282569574,1291380444,0
UMTS,262,2,801,86357,0,13.289106,52.53273,2400,3,1,1282569574,1298860769,0
UMTS,262,3,1107,83603,0,13.349675,52.497575,3102,222,1,1282672189,1300710809,0
GSM,262,2,776,867,0,13.349711,52.497367,1000,214,1,1282672189,1301575206,0
GSM,262,3,1107,13971,0,13.349743,52.497437,1000,212,1,1282672189,1300710809,0
GSM,262,3,1107,355,0,13.34963,52.497378,1000,198,1,1282672189,1300710809,0
```

## UnexpectedMessage When insert into csv data

```
[w@w-manjaro Downloads]$ clickhouse-client --port 9528 --query "INSERT INTO cell_towers.cell_towers FORMAT CSV" < cell_towers_no_headers.csv
Received exception from server (version 2021.5.0):
Code: 104. DB::Exception: Received from localhost:9528. UnexpectedMessage. Got unexpected message.
```

## My Computer Information(screenfetch -n)
```
 w@w-manjaro
 OS: Manjaro 21.0.6 Ornara
 Kernel: x86_64 Linux 5.12.8-1-MANJARO
 Uptime: 3h 59m
 Packages: 1490
 Shell: bash 5.1.8
 Resolution: 1920x1080
 DE: KDE 5.82.0 / Plasma 5.21.5
 WM: KWin
 GTK Theme: Adwaita-dark [GTK2/3]
 Icon Theme: breeze-dark
 Disk: 183G / 476G (41%)
 CPU: AMD Ryzen 5 4600H with Radeon Graphics @ 12x 3GHz
 GPU: AMD RENOIR (DRM 3.40.0, 5.12.8-1-MANJARO, LLVM 11.1.0)
 RAM: 4555MiB / 15438MiB
```

**Comment by jinmingjian** [comment] 2021-06-13 01:42
@pymongo I am also working with Linux jin-xeon 5.12.8-1-MANJARO. There is no problem for your 10-row sample. It will be interesting if AMD Ryzen 5 matters?...

```sql
TensorBase :) select * from cell_towers

SELECT *
FROM cell_towers

Query id: 3a4e0e44-1117-47a6-abf8-ac1e6037d084

┌─area─┬─averageSignal─┬───cell─┬─changeable─┬─────────────created─┬───────lat─┬───────lon─┬─mcc─┬─net─┬─radio─┬─range─┬─samples─┬─unit─┬─────────────updated─┐
│  801 │             0 │  86355 │          1 │ 2010-08-23 21:19:34 │ 52.522202 │ 13.285512 │ 262 │   2 │ UMTS  │  1000 │       7 │    0 │ 2011-03-15 10:15:41 │
│  801 │             0 │   1795 │          1 │ 2010-08-23 21:19:34 │ 52.525714 │ 13.276907 │ 262 │   2 │ GSM   │  5716 │       9 │    0 │ 2011-03-15 10:15:41 │
│  801 │             0 │   1794 │          1 │ 2010-08-23 21:19:34 │    52.524 │ 13.285064 │ 262 │   2 │ GSM   │  6280 │      13 │    0 │ 2011-03-22 20:16:47 │
│  801 │             0 │ 211250 │          1 │ 2010-08-23 21:19:34 │ 52.521744 │ 13.285446 │ 262 │   2 │ UMTS  │  1000 │       3 │    0 │ 2011-03-07 11:02:35 │
│  801 │             0 │  86353 │          1 │ 2010-08-23 21:19:34 │ 52.521515 │ 13.293457 │ 262 │   2 │ UMTS  │  1000 │       2 │    0 │ 2010-12-03 20:47:24 │
│  801 │             0 │  86357 │          1 │ 2010-08-23 21:19:34 │  52.53273 │ 13.289106 │ 262 │   2 │ UMTS  │  2400 │       3 │    0 │ 2011-02-28 10:39:29 │
│ 1107 │             0 │  83603 │          1 │ 2010-08-25 01:49:49 │ 52.497575 │ 13.349675 │ 262 │   3 │ UMTS  │  3102 │     222 │    0 │ 2011-03-21 20:33:29 │
│  776 │             0 │    867 │          1 │ 2010-08-25 01:49:49 │ 52.497367 │ 13.349711 │ 262 │   2 │ GSM   │  1000 │     214 │    0 │ 2011-03-31 20:40:06 │
│ 1107 │             0 │  13971 │          1 │ 2010-08-25 01:49:49 │ 52.497437 │ 13.349743 │ 262 │   3 │ GSM   │  1000 │     212 │    0 │ 2011-03-21 20:33:29 │
│ 1107 │             0 │    355 │          1 │ 2010-08-25 01:49:49 │ 52.497378 │  13.34963 │ 262 │   3 │ GSM   │  1000 │     198 │    0 │ 2011-03-21 20:33:29 │
└──────┴───────────────┴────────┴────────────┴─────────────────────┴───────────┴───────────┴─────┴─────┴───────┴───────┴─────────┴──────┴─────────────────────┘
```

**Comment by jinmingjian** [comment] 2021-06-14 03:30
@pymongo it is confirmed. The new client (>=21.5) has some trailing packets. The workaround is that to use the CH client of which version < 21.5. For example, [our repacked client in release page](https://github.com/tensorbase/tensorbase/releases/tag/v2021.06.14).

**Comment by pymongo** [comment] 2021-06-24 12:14
for clickhouse-client(>=21.5)  need to add compression arg `clickhouse-client --compression true`

client need compression arg to let tensorbase's server parse success

**Comment by jinmingjian** [comment] 2021-06-24 13:44
@pymongo Cool discovery! I have not investigated the detail problem.  If we enable the compression flag, could your csv case pass successfully?

**Comment by jinmingjian** [comment] 2021-06-25 01:36
It is confirmed that the compression flag has been changed to false. And this is interesting to show that our logic for raw packet has problem.

**Comment by pymongo** [comment] 2021-06-25 01:37
> @pymongo Cool discovery! I have not investigated the detail problem. If we enable the compression flag, could your csv case pass successfully?

Yes, ClickHouse client version 21.6.5.37 with compression arg insert csv data successfully!

I suggest to add `clickhouse-client version >=21.5 need --compression=true flag` to docuemnt get_started_users.md until this bug was fixed?

**Comment by jinmingjian** [comment] 2021-06-25 01:38
@pymongo  nice!  Can you submit a doc PR for this? :heart:

**Closed** 2021-06-26 12:10 UTC
Labels: component/server, type/bug
